### PR TITLE
Make fio-plot pip installable 

### PR DESCRIPTION
**Pull request by Flowrey**
Hi, seeing that the project was not available on pip I've decided to make the project pip install able (`pip3 install --user -e .` when inside of root project), you should now be able to push the code to PyPi and let users install it from there.
I've also added an entry points console_scripts in order to call the software from shell with the command `bench-fio` or `fio-plot ` and I have tried to improve project's structure.

### CODE REVIEW

**Comment by louwrentius** [comment]
So, I tested this pull request on a vanilla install of Ubuntu 18.04 LTS and it didn't quite work out of the box. 

I had to issue these commands to make it work. 

- apt install libjpeg-dev zlib1g-dev python3-pip
- pip3 install matplotlib numpy

The setup tools mechanism tries to install versions of numpy and matplotlib that are too new for this ubuntu version.
Pinning on specific versions doesn't seem right, but if we can clean out the pip and apt steps, that would be nice, any ideas? What OS did you try it on?

In the end, solving this by documentation is an option too.

On Ubuntu 20.04 LTS I get this error after a clean install:

- error: pyparsing 3.0.4 is installed but pyparsing<3,>=2.0.2 is required by {'packaging'}

```
Traceback (most recent call last):
  File "/usr/local/bin/bench-fio", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3254, in <module>
    def _initialize_master_working_set():
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3237, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3266, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 586, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 599, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 792, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (pyparsing 3.0.4 (/usr/local/lib/python3.8/dist-packages/pyparsing-3.0.4-py3.8.egg), Requirement.parse('pyparsing<3,>=2.0.2'), {'packaging'})

```

This error seems to be resolved by this change in setup.py:

`install_requires=['numpy>=1.19.0','matplotlib>=3.3.0','Pillow>=7.2.0', 'pyan3', 'pyparsing<3,>=2.0.2'],
`

Maybe can you include that in your code?

**Comment by Flowrey** [comment]
Hi, i work on Fedora 34 but pip should install package from the PyPi repository so it's shouldn't be too dependent of the OS except for maybe lib C dependents packages.
I've tried to build the application inside a docker container based on a Debian Stable minimal with the following line been changed in the setup.py : `install_requires=['numpy','matplotlib','Pillow', 'pyan3', 'pyparsing'],` and it works, the only package i had to download was `python3-pip`.
I've added the dockerfile and edit the setup.py

**Comment by louwrentius** [comment]
Ok, thanks for the extra effort of testing on Debian.
I'll probably update the installation instructions and give instructions for both Ubuntu, and Debian.  Does Fedora require anything special aside from pip3 ?

**Comment by Flowrey** [comment]
No i haven't had to download extra package to make it work

**Pull request merged**
